// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace main.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250605125502_AddEmailHashToUsers")]
    partial class AddEmailHashToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.AdoptionRequests", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("message")
                        .HasColumnType("text");

                    b.Property<Guid>("pet_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("pet_id");

                    b.HasIndex("user_id", "pet_id");

                    b.ToTable("AdoptionRequests", (string)null);
                });

            modelBuilder.Entity("Models.AdoptionStatuses", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("AdoptionStatuses", (string)null);
                });

            modelBuilder.Entity("Models.Breeds", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int>("species_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Breeds", (string)null);
                });

            modelBuilder.Entity("Models.Favorites", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("pet_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("pet_id");

                    b.HasIndex("user_id", "pet_id");

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("Models.Genders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Genders", (string)null);
                });

            modelBuilder.Entity("Models.News", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("content")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("image_url")
                        .HasColumnType("text");

                    b.Property<Guid>("shelter_id")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("News", (string)null);
                });

            modelBuilder.Entity("Models.Pets", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("age")
                        .HasColumnType("real");

                    b.Property<int>("breed_id")
                        .HasColumnType("integer");

                    b.Property<string>("category")
                        .HasColumnType("text");

                    b.Property<string>("cena")
                        .HasColumnType("text");

                    b.Property<string>("color")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("external_url")
                        .HasColumnType("text");

                    b.Property<int?>("gender_id")
                        .HasColumnType("integer");

                    b.Property<string>("image")
                        .HasColumnType("text");

                    b.Property<string>("mongo_image_id")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("photo_id")
                        .HasColumnType("text");

                    b.Property<Guid>("shelter_id")
                        .HasColumnType("uuid");

                    b.Property<int>("species_id")
                        .HasColumnType("integer");

                    b.Property<int>("status_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("breed_id");

                    b.HasIndex("external_url")
                        .IsUnique();

                    b.HasIndex("gender_id");

                    b.HasIndex("shelter_id");

                    b.HasIndex("species_id");

                    b.ToTable("Pets", (string)null);
                });

            modelBuilder.Entity("Models.Reviews", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("shelter_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("shelter_id");

                    b.HasIndex("user_id", "shelter_id");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Models.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Models.Shelters", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<Guid>("shelter_owner_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("shelter_owner_id");

                    b.ToTable("Shelters", (string)null);
                });

            modelBuilder.Entity("Models.Species", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Species", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "dog"
                        },
                        new
                        {
                            id = 2,
                            name = "cat"
                        },
                        new
                        {
                            id = 3,
                            name = "rabbit"
                        },
                        new
                        {
                            id = 4,
                            name = "bird"
                        },
                        new
                        {
                            id = 5,
                            name = "rodent"
                        },
                        new
                        {
                            id = 6,
                            name = "reptile"
                        },
                        new
                        {
                            id = 7,
                            name = "horse"
                        },
                        new
                        {
                            id = 8,
                            name = "fish"
                        },
                        new
                        {
                            id = 9,
                            name = "exotic"
                        });
                });

            modelBuilder.Entity("Models.Users", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("email_hash")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("name");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Models.AdoptionRequests", b =>
                {
                    b.HasOne("Models.Pets", null)
                        .WithMany()
                        .HasForeignKey("pet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Users", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Favorites", b =>
                {
                    b.HasOne("Models.Pets", null)
                        .WithMany()
                        .HasForeignKey("pet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Users", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Pets", b =>
                {
                    b.HasOne("Models.Breeds", "Breed")
                        .WithMany()
                        .HasForeignKey("breed_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Genders", "Gender")
                        .WithMany()
                        .HasForeignKey("gender_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.Shelters", "Shelter")
                        .WithMany()
                        .HasForeignKey("shelter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Species", "Species")
                        .WithMany()
                        .HasForeignKey("species_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Gender");

                    b.Navigation("Shelter");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Models.Reviews", b =>
                {
                    b.HasOne("Models.Shelters", null)
                        .WithMany()
                        .HasForeignKey("shelter_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Users", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Shelters", b =>
                {
                    b.HasOne("Models.Users", "Owner")
                        .WithMany("Shelters")
                        .HasForeignKey("shelter_owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Models.Users", b =>
                {
                    b.Navigation("Shelters");
                });
#pragma warning restore 612, 618
        }
    }
}
