CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AdoptionRequests" (
    id uuid NOT NULL,
    pet_id uuid NOT NULL,
    user_id uuid NOT NULL,
    message text,
    status text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AdoptionRequests" PRIMARY KEY (id)
);

CREATE TABLE "AdoptionStatuses" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text,
    CONSTRAINT "PK_AdoptionStatuses" PRIMARY KEY (id)
);

INSERT INTO "AdoptionStatuses" ("id", "name") VALUES
  (1, 'Available'),
  (2, 'Adopted'),
  (3, 'Pending')
ON CONFLICT ("id") DO NOTHING;

CREATE TABLE "Breeds" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    species_id integer NOT NULL,
    name text,
    CONSTRAINT "PK_Breeds" PRIMARY KEY (id)
);

CREATE TABLE "Favorites" (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    pet_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Favorites" PRIMARY KEY (id)
);

CREATE TABLE "Genders" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text,
    CONSTRAINT "PK_Genders" PRIMARY KEY (id)
);

INSERT INTO "Genders" ("id", "name") VALUES
  (1, 'Male'),
  (2, 'Female')
ON CONFLICT ("id") DO NOTHING;

CREATE TABLE "News" (
    id uuid NOT NULL,
    title text,
    content text,
    image_url text,
    created_at timestamp with time zone NOT NULL,
    shelter_id uuid NOT NULL,
    CONSTRAINT "PK_News" PRIMARY KEY (id)
);

CREATE TABLE "Pets" (
    id uuid NOT NULL,
    species_id integer NOT NULL,
    breed_id integer NOT NULL,
    gender_id integer NOT NULL,
    name text,
    age real NOT NULL,
    color text,
    health text,
    status_id integer NOT NULL,
    mongo_image_id text,
    description text,
    image text,
    created_at timestamp with time zone NOT NULL,
    shelter_id uuid NOT NULL,
    CONSTRAINT "PK_Pets" PRIMARY KEY (id)
);

CREATE TABLE "Reviews" (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    shelter_id uuid NOT NULL,
    comment text,
    rating integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY (id)
);

CREATE TABLE "Roles" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text,
    CONSTRAINT "PK_Roles" PRIMARY KEY (id)
);

CREATE TABLE "Shelters" (
    id uuid NOT NULL,
    shelter_owner_id uuid NOT NULL,
    name text,
    address text,
    phone text,
    email text,
    description text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Shelters" PRIMARY KEY (id)
);

CREATE TABLE "Species" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text,
    CONSTRAINT "PK_Species" PRIMARY KEY (id)
);

INSERT INTO "Species" ("id", "name") VALUES
  (1, 'Dogs'),
  (2, 'Cats'),
  (3, 'Rabbits'),
  (4, 'Birds'),
  (5, 'Rodents'),
  (6, 'Reptiles'),
  (7, 'Horses'),
  (8, 'Fish'),
  (9, 'Agricultural'),
  (999, 'Unknown')
ON CONFLICT ("id") DO NOTHING;

CREATE TABLE "Users" (
    id uuid NOT NULL,
    name text,
    email text,
    password text,
    role text,
    phone text,
    address text,
    CONSTRAINT "PK_Users" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250410102002_InitialCreate', '9.0.4');

CREATE INDEX "IX_Shelters_shelter_owner_id" ON "Shelters" (shelter_owner_id);

CREATE INDEX "IX_Pets_breed_id" ON "Pets" (breed_id);

CREATE INDEX "IX_Pets_gender_id" ON "Pets" (gender_id);

CREATE INDEX "IX_Pets_shelter_id" ON "Pets" (shelter_id);

CREATE INDEX "IX_Pets_species_id" ON "Pets" (species_id);

ALTER TABLE "Pets" ADD CONSTRAINT "FK_Pets_Breeds_breed_id" FOREIGN KEY (breed_id) REFERENCES "Breeds" (id) ON DELETE CASCADE;

ALTER TABLE "Pets" ADD CONSTRAINT "FK_Pets_Genders_gender_id" FOREIGN KEY (gender_id) REFERENCES "Genders" (id) ON DELETE CASCADE;

ALTER TABLE "Pets" ADD CONSTRAINT "FK_Pets_Shelters_shelter_id" FOREIGN KEY (shelter_id) REFERENCES "Shelters" (id) ON DELETE CASCADE;

ALTER TABLE "Pets" ADD CONSTRAINT "FK_Pets_Species_species_id" FOREIGN KEY (species_id) REFERENCES "Species" (id) ON DELETE CASCADE;

ALTER TABLE "Shelters" ADD CONSTRAINT "FK_Shelters_Users_shelter_owner_id" FOREIGN KEY (shelter_owner_id) REFERENCES "Users" (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250430091619_AddModelRelationships', '9.0.4');

CREATE INDEX "IX_Reviews_shelter_id" ON "Reviews" (shelter_id);

CREATE INDEX "IX_Reviews_user_id" ON "Reviews" (user_id);

CREATE INDEX "IX_Favorites_pet_id" ON "Favorites" (pet_id);

CREATE INDEX "IX_Favorites_user_id" ON "Favorites" (user_id);

CREATE INDEX "IX_AdoptionRequests_pet_id" ON "AdoptionRequests" (pet_id);

CREATE INDEX "IX_AdoptionRequests_user_id" ON "AdoptionRequests" (user_id);

ALTER TABLE "AdoptionRequests" ADD CONSTRAINT "FK_AdoptionRequests_Pets_pet_id" FOREIGN KEY (pet_id) REFERENCES "Pets" (id) ON DELETE CASCADE;

ALTER TABLE "AdoptionRequests" ADD CONSTRAINT "FK_AdoptionRequests_Users_user_id" FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE;

ALTER TABLE "Favorites" ADD CONSTRAINT "FK_Favorites_Pets_pet_id" FOREIGN KEY (pet_id) REFERENCES "Pets" (id) ON DELETE CASCADE;

ALTER TABLE "Favorites" ADD CONSTRAINT "FK_Favorites_Users_user_id" FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE;

ALTER TABLE "Reviews" ADD CONSTRAINT "FK_Reviews_Shelters_shelter_id" FOREIGN KEY (shelter_id) REFERENCES "Shelters" (id) ON DELETE CASCADE;

ALTER TABLE "Reviews" ADD CONSTRAINT "FK_Reviews_Users_user_id" FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250507071937_AddMoreRelationships', '9.0.4');

ALTER TABLE "Pets" ADD external_url text;

ALTER TABLE "Pets" ADD photo_id text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250523064212_PetParserAddition', '9.0.4');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250523170604_PetParserGenders', '9.0.4');

ALTER TABLE "Pets" ADD cena text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250524114424_PetsCenapracing', '9.0.4');

ALTER TABLE "Pets" DROP COLUMN health;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250529125232_RemoveColorAndHealthFromPets', '9.0.4');

ALTER TABLE "Pets" ALTER COLUMN gender_id DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250529134222_MakeGenderNullable', '9.0.4');

ALTER TABLE "Pets" ALTER COLUMN age DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250529141517_MakeAgeNullable', '9.0.4');

INSERT INTO "Species" ("id", "name") VALUES (999, 'Unknown') ON CONFLICT ("id") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250530150841_AddUnknownSpecies', '9.0.4');

INSERT INTO "Species" ("id", "name") VALUES (999, 'Unknown') ON CONFLICT ("id") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250530151317_AddUnknownSpecie', '9.0.4');

DROP INDEX "IX_Reviews_user_id";

DROP INDEX "IX_Favorites_user_id";

DROP INDEX "IX_AdoptionRequests_user_id";

ALTER TABLE "Pets" ADD category text;

CREATE UNIQUE INDEX "IX_Users_email" ON "Users" (email);

CREATE INDEX "IX_Users_name" ON "Users" (name);

CREATE UNIQUE INDEX "IX_Shelters_email" ON "Shelters" (email);

CREATE INDEX "IX_Reviews_user_id_shelter_id" ON "Reviews" (user_id, shelter_id);

CREATE UNIQUE INDEX "IX_Pets_external_url" ON "Pets" (external_url);

CREATE INDEX "IX_Favorites_user_id_pet_id" ON "Favorites" (user_id, pet_id);

CREATE INDEX "IX_AdoptionRequests_user_id_pet_id" ON "AdoptionRequests" (user_id, pet_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250604171202_AddPetCategory', '9.0.4');

COMMIT;

